server:
  port: 8081
mybatis:
  type-aliases-package: cn.com.xhengz.weframe
  mapper-locations: classpath:mappings/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    default-executor-type: simple
    local-cache-scope: session
    jdbc-type-for-null: null

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weframe?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
debug: true

